### ISSUE TITLE
28th August 2014

### ISSUE THREAD

**Issue by achingbrain** [dimsumjs/london#1]
The first DimSumJS will happen between 12:30-2pm on Thursday 28th August 2014.

I'm open to restaurant recommendations but the current plan is [Young Cheng](https://plus.google.com/109034807470013243280/about?gl=uk&hl=en) on Lisle Street (not to be confused with the other Young Chengs on Shaftesbury Avenue or Wardour Street).

It gets pretty busy so we'll need to book - to give me an idea of numbers [reserve your spot](https://www.eventbrite.com/e/dimsumjs-august-2014-tickets-12631452013).

**Comment by aychtang** [comment]
Is this booked? See you all soon.

**Comment by achingbrain** [comment]
Yep, all booked. If I were to hazard a guess I'd say we'll be upstairs.

See you later.

**Comment by achingbrain** [comment]
Turns out we're downstairs at the back..

**Comment by herebebeasties** [comment]
That was excellent. Thanks for organising it!

**Comment by olizilla** [comment]
Best DimSumJS ever!
![image](https://cloud.githubusercontent.com/assets/58871/4076172/bce12f2a-2eb7-11e4-9231-17d9e1f7ecd2.png)

**Comment by achingbrain** [comment]
Great stuff, so glad everyone could make it.

I'll sort out a date for another one at the end of September.
