### ISSUE TITLE
25th September 2014

### ISSUE THREAD

**Issue by alanshaw** [dimsumjs/london#2]
@cavill knows the "best place" for dim sum in London. Where is it, what is it called?

**Comment by cavill** [comment]
@alanshaw this place! https://plus.google.com/110353869035995626971/about (Pearl Liang in Paddington)

**Comment by alanshaw** [comment]
:thumbsup:

**Comment by aychtang** [comment]
Can vouch for Pearl Liang

**Comment by alanshaw** [comment]
Also apparently this place is good http://plumvalleylondon.com/

**Comment by aychtang** [comment]
Can we make this more toward mid-late September? I haven't decided when I'm moving yet.

**Comment by achingbrain** [comment]
@alanshaw Wow, their website is a hive of scum and villainy - must be great.  I'll do a recce.

@cheeseen No problem, if we follow a "last Thursday of the month" type arrangement, that'd put it on the 25th September.

**Comment by achingbrain** [comment]
25th September it is - https://www.eventbrite.com/e/dimsumjs-september-2014-tickets-13115000319

Hopefully see you all there?
